apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
  namespace: three-tier
  labels: 
    role: api
    env: demo
spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailapiVersion: apps/v1
kind: Deployment

metadata:
  name: api
  namespace: three-tier

spec:
  replicas: 2

  selector:
    matchLabels:
      role: api

  template:
    metadata:
      labels:
        role: api

    spec:
      containers:
      - name: api

        image: 068799540153.dkr.ecr.eu-north-1.amazonaws.com/three-tier-backend:latest

        ports:
        - containerPort: 3500

        env:
        - name: MONGO_CONN_STR
          value: mongodb://mongodb-svc:27017/todo?directConnection=true

        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-sec
              key: username

        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-sec
              key: password

        livenessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
